### ISSUE TITLE
Use connection string inside Publish Profile

### ISSUE THREAD

**Issue by paschott** [RichieBzzzt/PoshSSDTBuildDeploy#34]
It would be really convenient to define the connection string inside the publish profile and allow us to toggle a switch to just use that instead of always providing a connection string. I like the ability to override, but I usually create profiles for the different servers I need to hit when they're internal as I usually only have a small number per database (Local, Dev, Test, Prod).

**Comment by RichieBzzzt** [comment]
Hello!

Sure, it will be quite easy to make this change. I’ll see if I can get it done this weekend.

**Comment by RichieBzzzt** [comment]
Completed as of #35 so use build (PoshSSDTBuildDeploy 2.0.338.0)
