### ISSUE TITLE
Unable to use Install-PackageProvider for NuGet?

### ISSUE THREAD

**Issue by paschott** [RichieBzzzt/PoshSSDTBuildDeploy#36]
Getting an error when trying to do the Install-PackageProvider for Nuget:
Install-PackageProvider -Name NuGet -Force -Scope CurrentUser

WARNING: Unable to download the list of available providers. Check your internet connection.
Install-PackageProvider : No match was found for the specified search criteria for the provider 'NuGet'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.
At C:\Development\hwtechnology\AdventureWorks.DB\scripts\ExecutPOSHSSDTBuildDeploy.ps1:17 char:5
+     Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-PackageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackageProvider
 
Importing PoshSSDTBuildDeploy.
WARNING: If DataToolsVersion is blank latest will be used
Cannot find nuget at path \nuget.exe
Downloading Latest copy of NuGet!
Invoke-WebRequest : Could not find a part of the path 'C:\WINDOWS\system32\Test\nuget.exe'.
At line:18 char:9
+         Invoke-WebRequest -Uri "https://dist.nuget.org/win-x86-comman ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
 
At least 4.6.1 is installed!
.NET Version is 4.6.1, DWORD Value is 461808 and Required Version is True
&.\Test\nuget.exe install Microsoft.Data.Tools.Msbuild -ExcludeVersion -OutputDirectory .\Test

It appears that the nuget install hasn't worked, check output above to see whats going on
At line:39 char:13
+             Throw "It appears that the nuget install hasn't worked, c ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (It appears that... whats going on:String) [], RuntimeException
    + FullyQualifiedErrorId : It appears that the nuget install hasn't worked, check output above to see whats going on

**Comment by RichieBzzzt** [comment]
Hello! 

Very unusual. Can I have a copy of your ExecutePoshssdtbuilddeploy? 

Obvious question, but box definitely has connection to internet?

**Comment by paschott** [comment]
I just copied the script from your "test this" Gist and am running that. It should be the latest version, but it hangs when it tries to install NuGet, then throws that error.

And yes - definitely connected to the internet. I see this when the Find-Module command is run.

Version    Name                                Repository           Description
-------    ----                                ----------           -----------                                                                                2.0.340.0  PoshSSDTBuildDeploy                 PSGallery            Build and Deploy SSDT

________________________________

**Comment by RichieBzzzt** [comment]
Alright cheers will investigate.

**Comment by paschott** [comment]
Mostly seems to be an issue w/ the Nuget and Install-PackageProvider so probably outside of your control for the tests. Is there a workaround you'd recommend?  Just wanting to do some tests on our build box to see what fails there but if I can't get past the Nuget part, I could have some trouble.

Some 2-year-old posts I saw said disabling FIPS worked at the time, but that shouldn't still be the case and hopefully unnecessary.

Thanks.
________________________________

**Comment by paschott** [comment]
Hmm - might be that my WorkingFolder didn't exist. Will have to adjust the script to make sure that folder exists when putting it in as a parameter.  Also need to make sure that the command is running in the folder I think it should be in. I think it changed to my windows\system32 folder because I was running as admin.

Please close this issue. User error, apparently.
________________________________

**Comment by RichieBzzzt** [comment]
I did think that the workingfolder might be missing, from the error, but wanted to double check. 

I will close issue. Thanks for the feedback!
