### ISSUE TITLE
Support additional (newer) versions of MSBuild

### ISSUE THREAD

**Issue by alevyinroc** [RichieBzzzt/PoshSSDTBuildDeploy#65]
It appears that `Invoke-MsBuildSSDT` is written to only support Visual Studio 2017 and 2015 (msbuild 14 & 15).  I would prefer to not download an additional (older) version for my build servers.

Suggestion: If a path to build tools is specified, use that path instead of hardcoding the path (line 65 currently). VS 2019 installs `msbuild.exe` to `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin` by default.

Other option: add the above path as another one to be searched by the function.

**Comment by RichieBzzzt** [comment]
Hello! 

Yes good point will update and get a new version out this week.

**Comment by RichieBzzzt** [comment]
OK added param so that msbuild path can be added - 

https://github.com/RichieBzzzt/PoshSSDTBuildDeploy/blob/72fa4f4957f095c5d40fdf1f665e58e0cb9714c1/PoshSSDTBuildDeploy/Functions/InvokeMSBuildSSDT.ps1#L44
